Goedecker pseudopotential for Ag
   47  11  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.57000000    1     0.03341912                                                 rloc nloc c1
    3                                                                               nnonloc
     0.52704461    3     9.58204535    -5.27424043     0.99704725                   rs ns hs11 hs12 hs13
                                        8.43071259    -2.57436494                              hs22 hs23
                                                       2.04333882                                   hs33
     0.62911218    2     3.87401904    -1.74211583                                  rp np hp11 hp12
                                        2.06129925                                             hp22
                         0.25749375    -0.41140313                                        kp11 kp12
                                        0.48677875                                             kp22
     0.40538186    2    -2.72495276    -0.43354851                                  rd nd hd11 hd12
                                        0.49159781                                             hd22
                        -0.04679548     0.08682477                                        kd11 kd12
                                       -0.09845003                                             kd22
