Goedecker pseudopotential for Ar
   18   8  070301 zatom,zion,pspdat
10 11  1 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.40000000    1    -7.10000000                                                 rloc nloc c1
    2                                                                               nnonloc
     0.31881468    2    17.25203807    -5.58548836                                  rs ns hs11 hs12
                                        7.21083447                                             hs22
     0.35337019    2     4.97421551     0.00000000                                  rp np hp11 hp12
                                        0.00000000                                             hp22
                         0.05709588    -0.03927810                                        kp11 kp12
                                        0.04647447                                             kp22
