Goedecker pseudopotential for Au
   79  11  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.59000000    1    10.51717881                                                 rloc nloc c1
    3                                                                               nnonloc
     0.54384733    2     5.78681103    -2.25067966                                  rs ns hs11 hs12
                                        2.90561495                                             hs22
     0.60917298    2     4.28404873    -4.07128520                                  rp np hp11 hp12
                                        4.81720962                                             hp22
                         1.21911104    -2.38187511                                        kp11 kp12
                                        2.81827264                                             kp22
     0.43730922    2    -7.40328124     3.01019307                                  rd nd hd11 hd12
                                       -3.41323811                                             hd22
                        -0.12113041     0.26246301                                        kd11 kd12
                                       -0.29760507                                             kd22
