Goedecker pseudopotential for Br
   35   7  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.50000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.43803892    3     6.07855632     0.33049817    -1.23838226                   rs ns hs11 hs12 hs13
                                       -2.44090020     3.19748924                              hs22 hs23
                                                      -2.53792841                                   hs33
     0.45313561    2     2.45930381     0.52275313                                  rp np hp11 hp12
                                       -0.61852985                                             hp22
                         0.17300601    -0.09956873                                        kp11 kp12
                                        0.11781131                                             kp22
     0.56771383    1     0.55926645                                                 rd nd hd11
                         0.00654644                                                       kd11
