Goedecker pseudopotential for Cl
   17   7  070301 zatom,zion,pspdat
10 11  1 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.41000000    1    -6.39208181                                                 rloc nloc c1
    2                                                                               nnonloc
     0.33953864    2    15.21898983    -4.93452321                                  rs ns hs11 hs12
                                        6.37044208                                             hs22
     0.37847416    2     4.33877527     0.00000000                                  rp np hp11 hp12
                                        0.00000000                                             hp22
                         0.04528923    -0.03257832                                        kp11 kp12
                                        0.03854719                                             kp22
