Goedecker pseudopotential for Cu
   29  11  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.53000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.43135505    3     9.69380507    -6.47016535     1.93595215                   rs ns hs11 hs12 hs13
                                       11.50177396    -4.99860696                              hs22 hs23
                                                       3.96752127                                   hs33
     0.56139155    2     2.54547330    -0.78463573                                  rp np hp11 hp12
                                        0.92839352                                             hp22
                         0.09147262    -0.11244872                                        kp11 kp12
                                        0.13305111                                             kp22
     0.26455485    1   -12.82861406                                                 rd nd hd11
                         0.01046090                                                       kd11
