Goedecker pseudopotential for F
    9   7  070301 zatom,zion,pspdat
10 11  1 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.21492959    2   -21.57302836     3.19977615                                  rloc nloc c1 c2
    2                                                                               nnonloc
     0.19468402    1    23.74354045                                                 rs ns hs11
     0.18615608    1     0.00000000                                                 rp np hp11
                         0.01261401                                                       kp11
