Goedecker pseudopotential for Ga
   31  13  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.49000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.41677723    3    10.47568975    -4.92176814     0.87070559                   rs ns hs11 hs12 hs13
                                        7.77017809    -2.24815216                              hs22 hs23
                                                       1.78441545                                   hs33
     0.56962652    2     1.77798534     0.19585976                                  rp np hp11 hp12
                                       -0.23174439                                             hp22
                         0.07922219    -0.05277747                                        kp11 kp12
                                        0.06244715                                             kp22
     0.23812650    1   -16.24868022                                                 rd nd hd11
                         0.01545711                                                       kd11
