Goedecker pseudopotential for Ge
   32   4  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.54000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.42186518    3     7.51024121    -0.58810836    -1.44797580                   rs ns hs11 hs12 hs13
                                       -1.59588819     3.73865744                              hs22 hs23
                                                      -2.96746735                                   hs33
     0.56752887    2     0.91385969     0.54687534                                  rp np hp11 hp12
                                       -0.64707163                                             hp22
                         0.07515712    -0.03426241                                        kp11 kp12
                                        0.04053983                                             kp22
     0.81391394    1     0.19717731                                                 rd nd hd11
                         0.00209896                                                       kd11
