Goedecker pseudopotential for In
   49   3  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.61000000    1     5.08622849                                                 rloc nloc c1
    3                                                                               nnonloc
     0.68888318    3     0.56228376     0.99900413    -0.48093816                   rs ns hs11 hs12 hs13
                                       -2.07195476     1.24177699                              hs22 hs23
                                                      -0.98562993                                   hs33
     0.76370974    2     0.10892299     0.42327835                                  rp np hp11 hp12
                                       -0.50082970                                             hp22
                         0.10576704    -0.01722946                                        kp11 kp12
                                        0.02038617                                             kp22
     1.14391192    1     0.11683948                                                 rd nd hd11
                         0.00226126                                                       kd11
