Goedecker pseudopotential for In
   49  13  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.53000000    1     3.32478546                                                 rloc nloc c1
    3                                                                               nnonloc
     0.47949521    3    11.11716024    -6.57350729     1.50686327                   rs ns hs11 hs12 hs13
                                       10.93727471    -3.89070422                              hs22 hs23
                                                       3.08815074                                   hs33
     0.56993285    2     4.70061419    -2.21706406                                  rp np hp11 hp12
                                        2.62326557                                             hp22
                         0.34177179    -0.54199431                                        kp11 kp12
                                        0.64129631                                             kp22
     0.37706890    2    -4.00228785    -0.84012846                                  rd nd hd11 hd12
                                        0.95261614                                             hd22
                        -0.07755078     0.13327922                                        kd11 kd12
                                       -0.15112443                                             kd22
