Goedecker pseudopotential for Ir
   77   9  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.64100000    1    14.58181397                                                 rloc nloc c1
    3                                                                               nnonloc
     0.51010474    2     3.71524999    -1.26263745                                  rs ns hs11 hs12
                                        1.63005794                                             hs22
     0.68489160    2     1.91910152    -1.89619458                                  rp np hp11 hp12
                                        2.24360769                                             hp22
                         0.67464477    -1.13818413                                        kp11 kp12
                                        1.34671763                                             kp22
     0.47173508    2    -8.85603130     3.17025312                                  rd nd hd11 hd12
                                       -3.59472915                                             hd22
                        -0.15231734     0.28618874                                        kd11 kd12
                                       -0.32450753                                             kd22
