Goedecker pseudopotential for K
   19   9  070301 zatom,zion,pspdat
10 11  1 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.40000000    2    -3.36355184    -1.08652975                                  rloc nloc c1 c2
    2                                                                               nnonloc
     0.30531772    2    17.85062321    -5.62264870                                  rs ns hs11 hs12
                                        7.25880826                                             hs22
     0.31648432    2     7.33378021    -2.46094505                                  rp np hp11 hp12
                                        2.91182945                                             hp22
                         0.08936707    -0.06986008                                        kp11 kp12
                                        0.08265956                                             kp22
