Goedecker pseudopotential for Mn
   25  15  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.36500000    2     6.09304649    -0.44646948                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.29568592    2     1.88711984     6.35683658                                  rs ns hs11 hs12
                                       -8.20664074                                             hs22
     0.24561261    2    -6.57002452     7.98335983                                  rp np hp11 hp12
                                       -9.44603874                                             hp22
                         0.18314922    -0.04673645                                        kp11 kp12
                                        0.05529931                                             kp22
     0.22252279    1   -11.61205092                                                 rd nd hd11
                         0.00951135                                                       kd11
