Goedecker pseudopotential for N
    7   5  070301 zatom,zion,pspdat
10 11  1 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.28379051    2   -12.41522559     1.86809592                                  rloc nloc c1 c2
    2                                                                               nnonloc
     0.25540500    1    13.63026257                                                 rs ns hs11
     0.24549453    1     0.00000000                                                 rp np hp11
                         0.00414750                                                       kp11
