Goedecker pseudopotential for Na
   11   9  070301 zatom,zion,pspdat
10 11  1 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.23652322    2     0.29510499    -0.91388488                                  rloc nloc c1 c2
    2                                                                               nnonloc
     0.14356046    1    34.60149228                                                 rs ns hs11
     0.12993224    1   -14.27746168                                                 rp np hp11
                         0.05324287                                                       kp11
