Goedecker pseudopotential for Pb
   82   4  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.61750000    1     4.67238428                                                 rloc nloc c1
    3                                                                               nnonloc
     0.62235881    3     0.87991768     2.08114784    -1.43125710                   rs ns hs11 hs12 hs13
                                       -5.01469016     3.69548994                              hs22 hs23
                                                      -2.93320421                                   hs33
     0.81200202    2     0.15345679     0.47889785                                  rp np hp11 hp12
                                       -0.56663958                                             hp22
                         0.27466972    -0.02305844                                        kp11 kp12
                                        0.02728312                                             kp22
     1.02501525    1     0.30170206                                                 rd nd hd11
                         0.01870296                                                       kd11
