Goedecker pseudopotential for Pd
   46  18  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.41000000    2    26.78365917    -4.93130594                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.33797077    2    -0.71872875     4.38486657                                  rs ns hs11 hs12
                                       -5.66083840                                             hs22
     0.41519591    2    -0.04624449    -1.07795233                                  rp np hp11 hp12
                                        1.27545040                                             hp22
                        -0.44546453     0.88057476                                        kp11 kp12
                                       -1.04191011                                             kp22
     0.44027049    2     1.63916358    -3.09368795                                  rd nd hd11 hd12
                                        3.50791241                                             hd22
                        -0.03119207     0.06201267                                        kd11 kd12
                                       -0.07031576                                             kd22
