Goedecker pseudopotential for Po
   84   6  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.59250000    1     8.13432566                                                 rloc nloc c1
    3                                                                               nnonloc
     0.80422357    3     0.32633408     0.10539986     0.52809414                   rs ns hs11 hs12 hs13
                                        0.72287456    -1.36353322                              hs22 hs23
                                                       1.08227094                                   hs33
     0.81703652    2     0.15801481     0.37530247                                  rp np hp11 hp12
                                       -0.44406387                                             hp22
                         0.23215645     0.02511538                                        kp11 kp12
                                       -0.02971692                                             kp22
     0.89014943    1     0.46253238                                                 rd nd hd11
                         0.02706723                                                       kd11
