Goedecker pseudopotential for Rh
   45   9  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.61900948    1     4.70454397                                                 rloc nloc c1
    3                                                                               nnonloc
     0.61332681    2     4.99320515    -1.92978191                                  rs ns hs11 hs12
                                        2.49133773                                             hs22
     0.69365000    2     2.53237506    -1.28086042                                  rp np hp11 hp12
                                        1.51553449                                             hp22
                         0.18034883    -0.29258721                                        kp11 kp12
                                        0.34619385                                             kp22
     0.37003772    2   -16.88260377    14.71821684                                  rd nd hd11 hd12
                                      -16.68888922                                             hd22
                        -0.03265865     0.10951165                                        kd11 kd12
                                       -0.12417454                                             kd22
