Goedecker pseudopotential for Rh
   45  17  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.42000000    2    26.20679340    -4.93738335                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.34544622    2    -0.45248232     3.89280438                                  rs ns hs11 hs12
                                       -5.02558885                                             hs22
     0.37838014    2    -0.94111242    -0.00569931                                  rp np hp11 hp12
                                        0.00674351                                             hp22
                         0.18648086     0.14716083                                        kp11 kp12
                                       -0.17412304                                             kp22
     0.43374725    2     1.57423622    -3.01217170                                  rd nd hd11 hd12
                                        3.41548166                                             hd22
                        -0.02161325     0.05073757                                        kd11 kd12
                                       -0.05753100                                             kd22
