Goedecker pseudopotential for Rn
   86   8  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.57000000    1    16.20061781                                                 rloc nloc c1
    3                                                                               nnonloc
     0.63480802    3    -0.58199405     0.80312797     0.29738605                   rs ns hs11 hs12 hs13
                                       -0.55313531    -0.76784748                              hs22 hs23
                                                       0.60946004                                   hs33
     0.64710877    2     0.16927880     0.30517348                                  rp np hp11 hp12
                                       -0.36108613                                             hp22
                         0.64375030    -0.05907890                                        kp11 kp12
                                        0.06990310                                             kp22
     0.80634271    1     0.51103874                                                 rd nd hd11
                         0.03732898                                                       kd11
