Goedecker pseudopotential for Sc
   21  11  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.38500000    2     8.21490030    -0.55705910                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.36361108    2     2.64653339     3.02108393                                  rs ns hs11 hs12
                                       -3.90020259                                             hs22
     0.24389778    2    -2.63482265     7.99213715                                  rp np hp11 hp12
                                       -9.45642421                                             hp22
                         0.20196646    -0.05799329                                        kp11 kp12
                                        0.06861858                                             kp22
     0.25320575    1    -8.16594769                                                 rd nd hd11
                         0.00480094                                                       kd11
