Goedecker pseudopotential for Se
   34   6  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.51000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.43246005    3     6.51810990    -0.22271639    -1.19612899                   rs ns hs11 hs12 hs13
                                       -1.65797833     3.08839178                              hs22 hs23
                                                      -2.45133498                                   hs33
     0.47049162    2     2.28126223     0.36533529                                  rp np hp11 hp12
                                       -0.43227055                                             hp22
                         0.15386757    -0.09508784                                        kp11 kp12
                                        0.11250945                                             kp22
     0.62560034    1     0.43979948                                                 rd nd hd11
                         0.00489231                                                       kd11
