Goedecker pseudopotential for Sr
   38  10  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.48000000    2     6.81095035    -1.19610979                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.27588581    2    21.28971943    -7.89903416                                  rs ns hs11 hs12
                                       10.19760926                                             hs22
     0.28174086    2    11.70905135   -10.96577673                                  rp np hp11 hp12
                                       12.97488200                                             hp22
                         1.34629459    -2.37169277                                        kp11 kp12
                                        2.80622473                                             kp22
     0.52108911    1     0.36053906                                                 rd nd hd11
                         0.00779193                                                       kd11
