Goedecker pseudopotential for Ta
   73   5  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.74400000    1     9.83934257                                                 rloc nloc c1
    3                                                                               nnonloc
     0.45239666    2     6.12338066    -2.16890335                                  rs ns hs11 hs12
                                        2.80004218                                             hs22
     0.75164390    2     1.64970103    -2.51481038                                  rp np hp11 hp12
                                        2.97556377                                             hp22
                         0.67406021    -1.28529463                                        kp11 kp12
                                        1.52078112                                             kp22
     0.50114181    2   -12.42334477     9.01473381                                  rd nd hd11 hd12
                                      -10.22174735                                             hd22
                        -0.08463039     0.21860129                                        kd11 kd12
                                       -0.24787056                                             kd22
