Goedecker pseudopotential for Tc
   43  15  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.43000000    2    27.30199947    -4.64715709                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.34617499    2    -0.37921852     3.34056578                                  rs ns hs11 hs12
                                       -4.31265188                                             hs22
     0.42346840    2    -0.24151639    -0.82215042                                  rp np hp11 hp12
                                        0.97278149                                             hp22
                         0.00672609     0.27805622                                        kp11 kp12
                                       -0.32900056                                             kp22
     0.43186468    2     1.21878473    -2.67400954                                  rd nd hd11 hd12
                                        3.03204182                                             hd22
                        -0.00760164     0.03277719                                        kd11 kd12
                                       -0.03716584                                             kd22
