Goedecker pseudopotential for Tl
   81   3  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.63000000    1     1.45272083                                                 rloc nloc c1
    3                                                                               nnonloc
     0.78076788    3     0.37973043     1.20912802    -0.45856792                   rs ns hs11 hs12 hs13
                                       -2.30683834     1.18401727                              hs22 hs23
                                                      -0.93978457                                   hs33
     0.89705009    2    -0.02423596     0.58235582                                  rp np hp11 hp12
                                       -0.68905269                                             hp22
                         0.18274699    -0.00921547                                        kp11 kp12
                                        0.01090389                                             kp22
     1.09379194    1     0.22764152                                                 rd nd hd11
                         0.01256903                                                       kd11
