Goedecker pseudopotential for W
   74   6  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.71900000    1    10.69989013                                                 rloc nloc c1
    3                                                                               nnonloc
     0.46755372    2     5.80350289    -2.07063257                                  rs ns hs11 hs12
                                        2.67317516                                             hs22
     0.72666463    2     1.78871915    -2.55415819                                  rp np hp11 hp12
                                        3.02212073                                             hp22
                         0.70941707    -1.36284306                                        kp11 kp12
                                        1.61253765                                             kp22
     0.49929065    2   -10.59832562     6.44789319                                  rd nd hd11 hd12
                                       -7.31122365                                             hd22
                        -0.10122950     0.22114149                                        kd11 kd12
                                       -0.25075088                                             kd22
