Goedecker pseudopotential for Xe
   54   8  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.56000000    1     8.03636262                                                 rloc nloc c1
    3                                                                               nnonloc
     0.53049420    3     2.23202148     1.20035836    -0.99849824                   rs ns hs11 hs12 hs13
                                       -3.17371348     2.57811136                              hs22 hs23
                                                      -2.04631245                                   hs33
     0.58177483    2     0.79698181     0.59123264                                  rp np hp11 hp12
                                       -0.69955590                                             hp22
                         0.27633099    -0.09115677                                        kp11 kp12
                                        0.10785815                                             kp22
     0.68554509    1     0.56018900                                                 rd nd hd11
                         0.01674755                                                       kd11
