Goedecker pseudopotential for Zr
   40  12  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.47000000    2     7.79605677    -1.89321030                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.25982885    2    23.38087417    -8.57193933                                  rs ns hs11 hs12
                                       11.06632609                                             hs22
     0.28896899    2     8.59276581    -5.37735808                                  rp np hp11 hp12
                                        6.36257589                                             hp22
                         1.00490626    -1.41611759                                        kp11 kp12
                                        1.67557293                                             kp22
     0.58124504    2     0.02781064     0.27686186                                  rd nd hd11 hd12
                                       -0.31393184                                             hd22
                        -0.00255322     0.01079629                                        kd11 kd12
                                       -0.01224184                                             kd22
