Goedecker pseudopotential for Al
   13   3  070301 zatom,zion,pspdat
10 11  1 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.45000000    1    -7.55476126                                                 rloc nloc c1
    2                                                                               nnonloc
     0.48743529    2     6.95993832    -1.88883584                                  rs ns hs11 hs12
                                        2.43847659                                             hs22
     0.56218949    2     1.86529857     0.00000000                                  rp np hp11 hp12
                                        0.00000000                                             hp22
                         0.01323750    -0.01265070                                        kp11 kp12
                                        0.01496851                                             kp22
