Goedecker pseudopotential for As
   33   5  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.52000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.45554957    3     5.52067327     0.03512220    -1.06108239                   rs ns hs11 hs12 hs13
                                       -1.77119320     2.73970295                              hs22 hs23
                                                      -2.17457180                                   hs33
     0.55460557    2     1.02179156     0.62920826                                  rp np hp11 hp12
                                       -0.74448925                                             hp22
                         0.07884496    -0.03308528                                        kp11 kp12
                                        0.03914703                                             kp22
     0.70368872    1     0.31479504                                                 rd nd hd11
                         0.00335570                                                       kd11
