Goedecker pseudopotential for At
   85   7  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.58000000    1    14.21716853                                                 rloc nloc c1
    3                                                                               nnonloc
     0.66580683    3    -0.37891203     0.66112626     0.27884944                   rs ns hs11 hs12 hs13
                                       -0.39996168    -0.71998616                              hs22 hs23
                                                       0.57147130                                   hs33
     0.65241195    2     0.26704745     0.32622823                                  rp np hp11 hp12
                                       -0.38599845                                             hp22
                         0.66100264    -0.11918597                                        kp11 kp12
                                        0.14102275                                             kp22
     0.85406059    1     0.45259467                                                 rd nd hd11
                         0.03023997                                                       kd11
