Goedecker pseudopotential for Bi
   83   5  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.60500000    1     7.94575692                                                 rloc nloc c1
    3                                                                               nnonloc
     0.58223216    3     0.64373527     2.24761617    -1.44060063                   rs ns hs11 hs12 hs13
                                       -5.24479711     3.71961484                              hs22 hs23
                                                      -2.95235275                                   hs33
     0.76639400    2     0.21253292     0.37983417                                  rp np hp11 hp12
                                       -0.44942585                                             hp22
                         0.33910609    -0.02108594                                        kp11 kp12
                                        0.02494923                                             kp22
     0.96565479    1     0.34729822                                                 rd nd hd11
                         0.02035678                                                       kd11
