Goedecker pseudopotential for Ca
   20  10  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.39000000    2    -4.16707222    -1.58379781                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.28935572    2    20.53187635    -7.12978578                                  rs ns hs11 hs12
                                        9.20451387                                             hs22
     0.32788206    2     5.80560513    -0.42875336                                  rp np hp11 hp12
                                        0.50730782                                             hp22
                         0.15992263    -0.19967894                                        kp11 kp12
                                        0.23626331                                             kp22
     0.67961713    1     0.05806826                                                 rd nd hd11
                         0.00046474                                                       kd11
