Goedecker pseudopotential for Cd
   48  12  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.55000000    1     3.63395858                                                 rloc nloc c1
    3                                                                               nnonloc
     0.49127900    3    10.11138228    -6.50695409     1.80457679                   rs ns hs11 hs12 hs13
                                       11.33558598    -4.65939724                              hs22 hs23
                                                       3.69828191                                   hs33
     0.59970999    2     4.00148729    -1.88393578                                  rp np hp11 hp12
                                        2.22910288                                             hp22
                         0.28931079    -0.45543886                                        kp11 kp12
                                        0.53888253                                             kp22
     0.37787256    2    -6.13703223     1.53571055                                  rd nd hd11 hd12
                                       -1.74133209                                             hd22
                        -0.06128372     0.11410996                                        kd11 kd12
                                       -0.12938854                                             kd22
