Goedecker pseudopotential for Co
   27  17  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.35500000    2     4.82819736     0.36814301                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.27680076    2    -0.58449582     9.28629277                                  rs ns hs11 hs12
                                      -11.98855242                                             hs22
     0.26815783    2    -6.85195349     5.68013280                                  rp np hp11 hp12
                                       -6.72082376                                             hp22
                         0.03467390     0.13534705                                        kp11 kp12
                                       -0.16014479                                             kp22
     0.22258414    1   -12.33315019                                                 rd nd hd11
                         0.01143107                                                       kd11
