Goedecker pseudopotential for Cr
   24  14  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.37000000    2     5.69965764    -0.69548599                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.31393442    2     2.86995474     4.97445648                                  rs ns hs11 hs12
                                       -6.42199570                                             hs22
     0.24086624    2    -4.47620867     7.33141440                                  rp np hp11 hp12
                                       -8.67464650                                             hp22
                         0.19042071    -0.04824721                                        kp11 kp12
                                        0.05708687                                             kp22
     0.22028633    1   -11.19711641                                                 rd nd hd11
                         0.00894423                                                       kd11
