Goedecker pseudopotential for Ga
   31   3  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.56000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.56586645    3     2.21575051     1.03244793    -0.76062946                   rs ns hs11 hs12 hs13
                                       -2.57004845     1.96393682                              hs22 hs23
                                                      -1.55882652                                   hs33
     0.64671613    2     0.31122394     0.61341605                                  rp np hp11 hp12
                                       -0.72580366                                             hp22
                         0.04378597    -0.01162286                                        kp11 kp12
                                        0.01375235                                             kp22
     0.99942484    1     0.08951951                                                 rd nd hd11
                         0.00090534                                                       kd11
