Goedecker pseudopotential for I
   53   7  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.56000000    1     8.20710157                                                 rloc nloc c1
    3                                                                               nnonloc
     0.53192813    3     2.30814581     1.00390933    -0.95915606                   rs ns hs11 hs12 hs13
                                       -2.85610882     2.47653030                              hs22 hs23
                                                      -1.96568498                                   hs33
     0.58918244    2     0.90648219     0.42507060                                  rp np hp11 hp12
                                       -0.50295032                                             hp22
                         0.27569304    -0.10630683                                        kp11 kp12
                                        0.12578393                                             kp22
     0.73972147    1     0.47919458                                                 rd nd hd11
                         0.01290065                                                       kd11
