Goedecker pseudopotential for Kr
   36   8  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.50000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.42165717    3     6.46530358     0.53866049    -1.50260118                   rs ns hs11 hs12 hs13
                                       -3.13938870     3.87969957                              hs22 hs23
                                                      -3.07941607                                   hs33
     0.43374437    2     2.60116535     0.70510978                                  rp np hp11 hp12
                                       -0.83429715                                             hp22
                         0.19991623    -0.11006240                                        kp11 kp12
                                        0.13022759                                             kp22
     0.52469073    1     0.63559472                                                 rd nd hd11
                         0.00829734                                                       kd11
