Goedecker pseudopotential for Mg
   12   2  070301 zatom,zion,pspdat
10 11  1 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.57696017    1    -2.69040744                                                 rloc nloc c1
    2                                                                               nnonloc
     0.59392350    2     3.50321099    -0.71677167                                  rs ns hs11 hs12
                                        0.92534825                                             hs22
     0.70715728    1     0.83115848                                                 rp np hp11
                         0.00414275                                                       kp11
