Goedecker pseudopotential for Mo
   42  14  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.43000000    2    28.60936832    -4.72180336                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.34521579    2     0.14630305     2.76200500                                  rs ns hs11 hs12
                                       -3.56573312                                             hs22
     0.41688762    2    -0.19078495    -0.72874402                                  rp np hp11 hp12
                                        0.86226156                                             hp22
                         0.10103602     0.15762775                                        kp11 kp12
                                       -0.18650767                                             kp22
     0.42050785    2     1.21681419    -2.68646267                                  rd nd hd11 hd12
                                        3.04616234                                             hd22
                         0.00136004     0.02273862                                        kd11 kd12
                                       -0.02578317                                             kd22
