Goedecker pseudopotential for Nb
   41  13  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.46000000    2    26.27526252    -4.57803146                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.35116942    2    -1.04371870     3.27790404                                  rs ns hs11 hs12
                                       -4.23175592                                             hs22
     0.40546040    2    -0.66246647    -0.90782868                                  rp np hp11 hp12
                                        1.07415738                                             hp22
                         0.18261561     0.04502076                                        kp11 kp12
                                       -0.05326929                                             kp22
     0.42212155    2     1.49409323    -3.43003953                                  rd nd hd11 hd12
                                        3.88929925                                             hd22
                         0.00621330     0.01529808                                        kd11 kd12
                                       -0.01734639                                             kd22
