Goedecker pseudopotential for Ne
   10   8  070301 zatom,zion,pspdat
10 11  1 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.19000000    2   -27.12015973     4.36044962                                  rloc nloc c1 c2
    2                                                                               nnonloc
     0.17605938    2    28.17737082     0.83365601                                  rs ns hs11 hs12
                                       -1.07624528                                             hs22
     0.19547452    1    -0.23629360                                                 rp np hp11
                         0.01296979                                                       kp11
