Goedecker pseudopotential for Ni
   28  18  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.35000000    2     2.10216598     0.64848387                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.26129530    2     0.62265847     9.97022667                                  rs ns hs11 hs12
                                      -12.87150729                                             hs22
     0.22425346    2   -11.14270822    12.42956644                                  rp np hp11 hp12
                                      -14.70686134                                             hp22
                         0.13310966     0.15168114                                        kp11 kp12
                                       -0.17947154                                             kp22
     0.21534825    1   -12.62814550                                                 rd nd hd11
                         0.01349066                                                       kd11
