Goedecker pseudopotential for Os
   76   8  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.66700000    1    13.07904899                                                 rloc nloc c1
    3                                                                               nnonloc
     0.49576015    2     4.35033878    -1.49680274                                  rs ns hs11 hs12
                                        1.93236403                                             hs22
     0.70116140    2     1.81669550    -1.99815917                                  rp np hp11 hp12
                                        2.36425382                                             hp22
                         0.65252379    -1.16198770                                        kp11 kp12
                                        1.37488239                                             kp22
     0.47117333    2   -10.99598697     5.97918090                                  rd nd hd11 hd12
                                       -6.77975387                                             hd22
                        -0.12910182     0.26738080                                        kd11 kd12
                                       -0.30318133                                             kd22
