Goedecker pseudopotential for P
   15   5  070301 zatom,zion,pspdat
10 11  1 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.43000000    1    -5.87594327                                                 rloc nloc c1
    2                                                                               nnonloc
     0.39637742    2    11.00886207    -3.47035607                                  rs ns hs11 hs12
                                        4.48021042                                             hs22
     0.44829838    2     3.05606416     0.00000000                                  rp np hp11 hp12
                                        0.00000000                                             hp22
                         0.02606888    -0.02118456                                        kp11 kp12
                                        0.02506591                                             kp22
