Goedecker pseudopotential for Pd
   46  10  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.59600000    1     5.29987401                                                 rloc nloc c1
    3                                                                               nnonloc
     0.59194990    2     5.30819456    -2.06237933                                  rs ns hs11 hs12
                                        2.66252027                                             hs22
     0.66628526    2     2.73458446    -1.46697005                                  rp np hp11 hp12
                                        1.73574237                                             hp22
                         0.20640805    -0.35787163                                        kp11 kp12
                                        0.42343942                                             kp22
     0.43851839    2    -3.71978832    -0.80738825                                  rd nd hd11 hd12
                                        0.91549223                                             hd22
                        -0.06113102     0.10023162                                        kd11 kd12
                                       -0.11365198                                             kd22
