Goedecker pseudopotential for Pt
   78  10  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.61600000    1    11.31363525                                                 rloc nloc c1
    3                                                                               nnonloc
     0.55090426    2     4.73349110    -1.78459401                                  rs ns hs11 hs12
                                        2.30390096                                             hs22
     0.67413781    2     2.53479850    -1.77806555                                  rp np hp11 hp12
                                        2.10383553                                             hp22
                         0.68131890    -1.13737593                                        kp11 kp12
                                        1.34576135                                             kp22
     0.45739243    2    -7.26401101     2.55866480                                  rd nd hd11 hd12
                                       -2.90125318                                             hd22
                        -0.13179902     0.26337958                                        kd11 kd12
                                       -0.29864437                                             kd22
