Goedecker pseudopotential for Rb
   37   9  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.49000000    2     5.66908644    -0.81162703                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.28180292    2    21.39073240    -8.07866676                                  rs ns hs11 hs12
                                       10.42951394                                             hs22
     0.28570828    2    12.25634859   -12.19854075                                  rp np hp11 hp12
                                       14.43350807                                             hp22
                         1.41180234    -2.61453234                                        kp11 kp12
                                        3.09355639                                             kp22
     0.54179651    1     0.34566626                                                 rd nd hd11
                         0.00696032                                                       kd11
