Goedecker pseudopotential for Re
   75   7  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.69300000    1    11.96194160                                                 rloc nloc c1
    3                                                                               nnonloc
     0.46331539    2     6.08700876    -2.19137969                                  rs ns hs11 hs12
                                        2.82905901                                             hs22
     0.70964824    2     1.81506156    -2.35412193                                  rp np hp11 hp12
                                        2.78543463                                             hp22
                         0.69313998    -1.31294961                                        kp11 kp12
                                        1.55350293                                             kp22
     0.47606454    2   -12.39371002     8.00629664                                  rd nd hd11 hd12
                                       -9.07828707                                             hd22
                        -0.11238482     0.25543977                                        kd11 kd12
                                       -0.28964148                                             kd22
