Goedecker pseudopotential for Ru
   44  16  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.43000000    2    26.83239104    -5.05049720                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.34135508    2    -0.55504091     3.71548964                                  rs ns hs11 hs12
                                       -4.79667650                                             hs22
     0.42827085    2     0.10677508    -1.27757181                                  rp np hp11 hp12
                                        1.51164335                                             hp22
                        -0.15600415     0.48648402                                        kp11 kp12
                                       -0.57561565                                             kp22
     0.43814779    2     1.50921742    -2.94305440                                  rd nd hd11 hd12
                                        3.33711002                                             hd22
                        -0.01536873     0.04203938                                        kd11 kd12
                                       -0.04766818                                             kd22
