Goedecker pseudopotential for Ru
   44   8  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.61211332    1     5.04489332                                                 rloc nloc c1
    3                                                                               nnonloc
     0.64215040    2     4.62556355    -1.80334903                                  rs ns hs11 hs12
                                        2.32811359                                             hs22
     0.67936654    2     3.23395238    -2.42101064                                  rp np hp11 hp12
                                        2.86457842                                             hp22
                         0.24365860    -0.44245368                                        kp11 kp12
                                        0.52351826                                             kp22
     0.38059720    2   -15.53165455    13.58045054                                  rd nd hd11 hd12
                                      -15.39878349                                             hd22
                        -0.02436658     0.09258568                                        kd11 kd12
                                       -0.10498229                                             kd22
