Goedecker pseudopotential for S
   16   6  070301 zatom,zion,pspdat
10 11  1 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.42000000    1    -5.98626038                                                 rloc nloc c1
    2                                                                               nnonloc
     0.36482035    2    13.14354448    -4.24183045                                  rs ns hs11 hs12
                                        5.47617957                                             hs22
     0.40948048    2     3.70089057     0.00000000                                  rp np hp11 hp12
                                        0.00000000                                             hp22
                         0.03492359    -0.02660790                                        kp11 kp12
                                        0.03148290                                             kp22
