Goedecker pseudopotential for Sn
   50   4  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.60500000    1     6.26678230                                                 rloc nloc c1
    3                                                                               nnonloc
     0.56643732    3     1.57118124     1.47004118    -1.17857669                   rs ns hs11 hs12 hs13
                                       -3.81477013     3.04307193                              hs22 hs23
                                                      -2.41536347                                   hs33
     0.64184959    2     0.52689769     0.40325781                                  rp np hp11 hp12
                                       -0.47714107                                             hp22
                         0.22160101    -0.11203353                                        kp11 kp12
                                        0.13255986                                             kp22
     0.99087302    1     0.19876639                                                 rd nd hd11
                         0.00451584                                                       kd11
