Goedecker pseudopotential for Te
   52   6  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.57500000    1     8.71364868                                                 rloc nloc c1
    3                                                                               nnonloc
     0.57492240    3     1.40181273     0.97877992    -0.48630602                   rs ns hs11 hs12 hs13
                                       -2.05457624     1.25563675                              hs22 hs23
                                                      -0.99663078                                   hs33
     0.58989076    2     0.76478865     0.32398623                                  rp np hp11 hp12
                                       -0.38334568                                             hp22
                         0.28709255    -0.13816104                                        kp11 kp12
                                        0.16347435                                             kp22
     0.81338925    1     0.34485820                                                 rd nd hd11
                         0.00929869                                                       kd11
