Goedecker pseudopotential for V
   23  13  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.37500000    2     7.47470354    -0.37026363                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.32779544    2     1.94087762     4.72568824                                  rs ns hs11 hs12
                                       -6.10083728                                             hs22
     0.24476590    2    -5.97816705     9.35863915                                  rp np hp11 hp12
                                      -11.07329118                                             hp22
                         0.19032152    -0.05946067                                        kp11 kp12
                                        0.07035481                                             kp22
     0.24173879    1    -9.49989110                                                 rd nd hd11
                         0.00648186                                                       kd11
