Goedecker pseudopotential for Y
   39  11  070301 zatom,zion,pspdat
10 11  2 2 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.47500000    2    12.16776904    -2.32855103                                  rloc nloc c1 c2
    3                                                                               nnonloc
     0.24674070    2    23.45027195    -8.32535748                                  rs ns hs11 hs12
                                       10.74799029                                             hs22
     0.29656397    2     5.97863401    -5.85234964                                  rp np hp11 hp12
                                        6.92459348                                             hp22
                         1.23578364    -2.38648117                                        kp11 kp12
                                        2.82372260                                             kp22
     0.45045569    2     1.18749048    -1.31867331                                  rd nd hd11 hd12
                                        1.49523499                                             hd22
                         0.01304100    -0.00010639                                        kd11 kd12
                                        0.00012063                                             kd22
