Goedecker pseudopotential for Zn
   30  12  070301 zatom,zion,pspdat
10 11  2 0 2001 0  pspcod,pspxc,lmax,lloc,mmax,r2well
     0.51000000    0                                                                rloc nloc
    3                                                                               nnonloc
     0.40031644    3    11.53004133    -8.79189815     3.14508644                   rs ns hs11 hs12 hs13
                                       16.46577518    -8.12057827                              hs22 hs23
                                                       6.44550918                                   hs33
     0.54318233    2     2.59719512    -0.59426275                                  rp np hp11 hp12
                                        0.70314117                                             hp22
                         0.10017431    -0.10693277                                        kp11 kp12
                                        0.12652456                                             kp22
     0.25095885    1   -14.46695795                                                 rd nd hd11
                         0.01272732                                                       kd11
